server:
  port: 8082
  tomcat:
    basedir: ./
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60m
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: qrwf
  freemarker:
    suffix: .ftl
    cache: true
management:
  endpoints:
    web:
      base-path: /management
      path-mapping:
        health: health_check
      exposure:
        include: "*"
influx:
  url: http://127.0.0.1:8086 # 127.0.0.1 3.38.92.36
  username: edgecloud
  password: edge123!
  token: wsRkPDMrs0Vnu2RFU-IkFEBPxtgwqPGVD7clS3iMr9qOXrQynw0PTcMbQh7sOmLcLcJvf4-wcl1PtvZrYDSGiw==
  org: edgecloud
  bucket: bifrost
  logLevel: BODY # The log level for logging the HTTP request and HTTP response. (Default: NONE)
  readTimeout: 5s # Read timeout for OkHttpClient. (Default: 10s)
  writeTimeout: 5s # Write timeout for OkHttpClient. (Default: 10s)
  connectTimeout: 5s # Connection timeout for OkHttpClient. (Default: 10s)

